# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Robô Telegram Pro/lib/Views/UI/EditarImportarContaView.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(357, 300)
        Dialog.setMinimumSize(QtCore.QSize(357, 300))
        Dialog.setMaximumSize(QtCore.QSize(357, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/lib/Views/UI\\../Icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 70, 51, 21))
        self.label.setObjectName("label")
        self.labelTitulo_2 = QtWidgets.QLabel(Dialog)
        self.labelTitulo_2.setGeometry(QtCore.QRect(10, 20, 341, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo_2.setFont(font)
        self.labelTitulo_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitulo_2.setObjectName("labelTitulo_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 118, 51, 21))
        self.label_2.setObjectName("label_2")
        self.line_apelido = QtWidgets.QLineEdit(Dialog)
        self.line_apelido.setGeometry(QtCore.QRect(60, 118, 281, 20))
        self.line_apelido.setObjectName("line_apelido")
        self.btnSalvar = QtWidgets.QPushButton(Dialog)
        self.btnSalvar.setGeometry(QtCore.QRect(130, 260, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSalvar.setFont(font)
        self.btnSalvar.setStyleSheet("QPushButton:enabled {\n"
"    background-color: rgb(44, 163, 222);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color:rgb(185, 185, 185);\n"
"    color: white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/lib/Views/UI\\../Icons/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon1)
        self.btnSalvar.setObjectName("btnSalvar")
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setGeometry(QtCore.QRect(10, 190, 341, 41))
        self.label_status.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.label_conta = QtWidgets.QLabel(Dialog)
        self.label_conta.setGeometry(QtCore.QRect(60, 70, 281, 21))
        self.label_conta.setText("")
        self.label_conta.setObjectName("label_conta")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Editar Conta - Importação"))
        self.label.setText(_translate("Dialog", "Conta:"))
        self.labelTitulo_2.setText(_translate("Dialog", "Editar Conta"))
        self.label_2.setText(_translate("Dialog", "Apelido:"))
        self.btnSalvar.setText(_translate("Dialog", "Salvar"))

