# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Robô Telegram Pro/Views/UI/ExtrairListaView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(451, 363)
        Dialog.setMinimumSize(QtCore.QSize(411, 300))
        Dialog.setMaximumSize(QtCore.QSize(111111, 11111))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/Views/UI\\../Icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 381, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.comboGrupo = QtWidgets.QComboBox(Dialog)
        self.comboGrupo.setEnabled(False)
        self.comboGrupo.setGeometry(QtCore.QRect(20, 60, 421, 22))
        self.comboGrupo.setObjectName("comboGrupo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 35, 381, 31))
        self.label.setObjectName("label")
        self.lineNomeLista = QtWidgets.QLineEdit(Dialog)
        self.lineNomeLista.setEnabled(False)
        self.lineNomeLista.setGeometry(QtCore.QRect(170, 240, 221, 20))
        self.lineNomeLista.setObjectName("lineNomeLista")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 240, 151, 21))
        self.label_2.setObjectName("label_2")
        self.labelStatus = QtWidgets.QLabel(Dialog)
        self.labelStatus.setGeometry(QtCore.QRect(10, 270, 391, 41))
        self.labelStatus.setText("")
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setWordWrap(True)
        self.labelStatus.setObjectName("labelStatus")
        self.checkAtivos = QtWidgets.QCheckBox(Dialog)
        self.checkAtivos.setEnabled(False)
        self.checkAtivos.setGeometry(QtCore.QRect(20, 90, 181, 21))
        self.checkAtivos.setObjectName("checkAtivos")
        self.checkUsername = QtWidgets.QCheckBox(Dialog)
        self.checkUsername.setEnabled(False)
        self.checkUsername.setGeometry(QtCore.QRect(250, 90, 191, 21))
        self.checkUsername.setObjectName("checkUsername")
        self.btnSalvar = QtWidgets.QPushButton(Dialog)
        self.btnSalvar.setEnabled(False)
        self.btnSalvar.setGeometry(QtCore.QRect(150, 320, 150, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSalvar.setFont(font)
        self.btnSalvar.setStyleSheet("QPushButton:enabled {\n"
"    background-color: rgb(44, 163, 222);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color:rgb(185, 185, 185);\n"
"    color: white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/Views/UI\\../Icons/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon1)
        self.btnSalvar.setObjectName("btnSalvar")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 381, 20))
        self.label_5.setObjectName("label_5")
        self.spinDias = QtWidgets.QSpinBox(Dialog)
        self.spinDias.setEnabled(False)
        self.spinDias.setGeometry(QtCore.QRect(20, 200, 91, 31))
        self.spinDias.setMinimum(1)
        self.spinDias.setProperty("value", 7)
        self.spinDias.setObjectName("spinDias")
        self.checkRemoverAdministradores = QtWidgets.QCheckBox(Dialog)
        self.checkRemoverAdministradores.setEnabled(False)
        self.checkRemoverAdministradores.setGeometry(QtCore.QRect(20, 120, 191, 21))
        self.checkRemoverAdministradores.setObjectName("checkRemoverAdministradores")
        self.checkTelefone = QtWidgets.QCheckBox(Dialog)
        self.checkTelefone.setEnabled(False)
        self.checkTelefone.setGeometry(QtCore.QRect(250, 120, 191, 21))
        self.checkTelefone.setObjectName("checkTelefone")
        self.checkFoto = QtWidgets.QCheckBox(Dialog)
        self.checkFoto.setEnabled(False)
        self.checkFoto.setGeometry(QtCore.QRect(20, 150, 191, 21))
        self.checkFoto.setObjectName("checkFoto")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Extrair Lista"))
        self.label_7.setText(_translate("Dialog", "Extrair Lista"))
        self.label.setText(_translate("Dialog", "Extrair do Grupo:"))
        self.label_2.setText(_translate("Dialog", "Salvar lista com o nome:"))
        self.checkAtivos.setText(_translate("Dialog", "Apenas Membos Ativos"))
        self.checkUsername.setText(_translate("Dialog", "Apenas com Username"))
        self.btnSalvar.setText(_translate("Dialog", "Salvar"))
        self.label_5.setText(_translate("Dialog", "Visto por último:"))
        self.spinDias.setSuffix(_translate("Dialog", " Dias"))
        self.checkRemoverAdministradores.setText(_translate("Dialog", "Não Extrair Administradores"))
        self.checkTelefone.setText(_translate("Dialog", "Apenas com Telefone"))
        self.checkFoto.setText(_translate("Dialog", "Apenas Membros com Foto"))


