# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Robô Telegram Pro/lib/Views/UI/ImportarContaView.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(612, 425)
        Dialog.setMinimumSize(QtCore.QSize(612, 425))
        Dialog.setMaximumSize(QtCore.QSize(612, 425))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/lib/Views/UI\\../Icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.btnProcurar = QtWidgets.QPushButton(Dialog)
        self.btnProcurar.setGeometry(QtCore.QRect(490, 20, 111, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnProcurar.setFont(font)
        self.btnProcurar.setStyleSheet("QPushButton:enabled {\n"
"    background-color: rgb(44, 163, 222);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color:rgb(185, 185, 185);\n"
"    color: white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/lib/Views/UI\\../Icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnProcurar.setIcon(icon1)
        self.btnProcurar.setObjectName("btnProcurar")
        self.labelTitulo = QtWidgets.QLabel(Dialog)
        self.labelTitulo.setGeometry(QtCore.QRect(120, 20, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitulo.setFont(font)
        self.labelTitulo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitulo.setObjectName("labelTitulo")
        self.labelStatus = QtWidgets.QLabel(Dialog)
        self.labelStatus.setGeometry(QtCore.QRect(10, 350, 591, 41))
        self.labelStatus.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.labelStatus.setText("")
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setWordWrap(True)
        self.labelStatus.setObjectName("labelStatus")
        self.btnSalvar = QtWidgets.QPushButton(Dialog)
        self.btnSalvar.setGeometry(QtCore.QRect(260, 390, 91, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnSalvar.setFont(font)
        self.btnSalvar.setStyleSheet("QPushButton:enabled {\n"
"    background-color: rgb(44, 163, 222);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color:rgb(185, 185, 185);\n"
"    color: white;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/lib/Views/UI\\../Icons/diskette.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSalvar.setIcon(icon2)
        self.btnSalvar.setObjectName("btnSalvar")
        self.tableSessions = QtWidgets.QTableWidget(Dialog)
        self.tableSessions.setGeometry(QtCore.QRect(10, 50, 591, 301))
        self.tableSessions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableSessions.setObjectName("tableSessions")
        self.tableSessions.setColumnCount(3)
        self.tableSessions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSessions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSessions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSessions.setHorizontalHeaderItem(2, item)
        self.tableSessions.horizontalHeader().setDefaultSectionSize(150)
        self.tableSessions.horizontalHeader().setMinimumSectionSize(150)
        self.tableSessions.horizontalHeader().setStretchLastSection(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Importar Conta"))
        self.btnProcurar.setText(_translate("Dialog", "Carregar"))
        self.labelTitulo.setText(_translate("Dialog", "Importar Conta"))
        self.btnSalvar.setText(_translate("Dialog", "Salvar"))
        item = self.tableSessions.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Conta"))
        item = self.tableSessions.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Status"))
        item = self.tableSessions.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Observação"))



