# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/Robô Telegram Pro/Views/UI/LicenseView.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(432, 400)
        Dialog.setMinimumSize(QtCore.QSize(432, 400))
        Dialog.setMaximumSize(QtCore.QSize(432, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/Views/UI\\../Icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.lineCodigoAcesso = QtWidgets.QLineEdit(Dialog)
        self.lineCodigoAcesso.setEnabled(True)
        self.lineCodigoAcesso.setGeometry(QtCore.QRect(90, 241, 261, 20))
        self.lineCodigoAcesso.setAlignment(QtCore.Qt.AlignCenter)
        self.lineCodigoAcesso.setPlaceholderText("")
        self.lineCodigoAcesso.setObjectName("lineCodigoAcesso")
        self.labelStatus = QtWidgets.QLabel(Dialog)
        self.labelStatus.setGeometry(QtCore.QRect(0, 330, 431, 61))
        self.labelStatus.setText("")
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setWordWrap(True)
        self.labelStatus.setObjectName("labelStatus")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 160, 431, 41))
        self.label_4.setMinimumSize(QtCore.QSize(421, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(65, 65, 65)")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.btnValidar = QtWidgets.QPushButton(Dialog)
        self.btnValidar.setGeometry(QtCore.QRect(140, 281, 150, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnValidar.setFont(font)
        self.btnValidar.setStyleSheet("QPushButton:enabled {\n"
"    background-color: rgb(44, 163, 222);\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color:rgb(185, 185, 185);\n"
"    color: white;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/Views/UI\\../Icons/door-key.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnValidar.setIcon(icon1)
        self.btnValidar.setObjectName("btnValidar")
        self.labelLineCodigoAcesso = QtWidgets.QLabel(Dialog)
        self.labelLineCodigoAcesso.setGeometry(QtCore.QRect(10, 201, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.labelLineCodigoAcesso.setFont(font)
        self.labelLineCodigoAcesso.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLineCodigoAcesso.setWordWrap(True)
        self.labelLineCodigoAcesso.setObjectName("labelLineCodigoAcesso")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 347, 122))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:/Robô Telegram Pro/Views/UI\\../Icons/Logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.labelVersion = QtWidgets.QLabel(Dialog)
        self.labelVersion.setGeometry(QtCore.QRect(300, 370, 121, 20))
        self.labelVersion.setText("")
        self.labelVersion.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelVersion.setObjectName("labelVersion")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Licença"))
        self.label_4.setText(_translate("Dialog", "Validação de Licença"))
        self.btnValidar.setText(_translate("Dialog", "VALIDAR"))
        self.labelLineCodigoAcesso.setText(_translate("Dialog", "Informe o código de acesso presente no seu Painel WEB:"))

